//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailCheck.Spf.Poller.Rules {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SpfRulesMarkdownResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpfRulesMarkdownResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MailCheck.Spf.Poller.Rules.SpfRulesMarkdownResource", typeof(SpfRulesMarkdownResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AllMustBeLastMechanismErrorMessage {
            get {
                return ResourceManager.GetString("AllMustBeLastMechanismErrorMessage", resourceCulture);
            }
        }
        
        public static string DontUsePtrMechanismErrorMessage {
            get {
                return ResourceManager.GetString("DontUsePtrMechanismErrorMessage", resourceCulture);
            }
        }
        
        public static string ExplanationDoesntOccurMoreThanOnceErrorMessage {
            get {
                return ResourceManager.GetString("ExplanationDoesntOccurMoreThanOnceErrorMessage", resourceCulture);
            }
        }
        
        public static string ModifiersOccurAfterMechanismsErrorMessage {
            get {
                return ResourceManager.GetString("ModifiersOccurAfterMechanismsErrorMessage", resourceCulture);
            }
        }
        
        public static string OnlyOneSpfRecordErrorMessage {
            get {
                return ResourceManager.GetString("OnlyOneSpfRecordErrorMessage", resourceCulture);
            }
        }
        
        public static string RedirectDoesntOccurMoreThanOnceErrorMessage {
            get {
                return ResourceManager.GetString("RedirectDoesntOccurMoreThanOnceErrorMessage", resourceCulture);
            }
        }
        
        public static string RedirectModifierAndAllMechanismNotValidErrorMessage {
            get {
                return ResourceManager.GetString("RedirectModifierAndAllMechanismNotValidErrorMessage", resourceCulture);
            }
        }
        
        public static string ShouldBeSmallEnoughForUdp {
            get {
                return ResourceManager.GetString("ShouldBeSmallEnoughForUdp", resourceCulture);
            }
        }
        
        public static string ShouldNotHaveMoreThan10QueryLookupsErrorMessage {
            get {
                return ResourceManager.GetString("ShouldNotHaveMoreThan10QueryLookupsErrorMessage", resourceCulture);
            }
        }
        
        public static string CloseTo10QueryLookupsErrorMessage {
            get {
                return ResourceManager.GetString("CloseTo10QueryLookupsErrorMessage", resourceCulture);
            }
        }
        
        public static string QueryLookupsInfoMessage {
            get {
                return ResourceManager.GetString("QueryLookupsInfoMessage", resourceCulture);
            }
        }
        
        public static string ShouldNotUseMxInfoMessage {
            get {
                return ResourceManager.GetString("ShouldNotUseMxInfoMessage", resourceCulture);
            }
        }
    }
}
