//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailCheck.Spf.Poller.Rules {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SpfRulesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpfRulesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MailCheck.Spf.Poller.Rules.SpfRulesResource", typeof(SpfRulesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Last mechanism term should be “all” but was {1}..
        /// </summary>
        public static string AllMustBeLastMechanismErrorMessage {
            get {
                return ResourceManager.GetString("AllMustBeLastMechanismErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SPF specification limits the amount of DNS lookups for a record to 10. This record currently has {0} which could be taken over the limit by a third party change..
        /// </summary>
        public static string CloseTo10QueryLookupsErrorMessage {
            get {
                return ResourceManager.GetString("CloseTo10QueryLookupsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Record should not contain “ptr”..
        /// </summary>
        public static string DontUsePtrMechanismErrorMessage {
            get {
                return ResourceManager.GetString("DontUsePtrMechanismErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Record should not contain &apos;exp&apos; more than once. This record has {1} &apos;exp&apos; terms..
        /// </summary>
        public static string ExplanationDoesntOccurMoreThanOnceErrorMessage {
            get {
                return ResourceManager.GetString("ExplanationDoesntOccurMoreThanOnceErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Mechanisms (“a”, ”mx”, ”ptr”, ”ip4”, ”ip6”, ”exists”) should appear before modifiers (“redirect”, “exp”)..
        /// </summary>
        public static string ModifiersOccurAfterMechanismsErrorMessage {
            get {
                return ResourceManager.GetString("ModifiersOccurAfterMechanismsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Domain should have exactly 1 SPF record. This domain has {1}..
        /// </summary>
        public static string OnlyOneSpfRecordErrorMessage {
            get {
                return ResourceManager.GetString("OnlyOneSpfRecordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/10 DNS lookups used..
        /// </summary>
        public static string QueryLookupsInfoMessage {
            get {
                return ResourceManager.GetString("QueryLookupsInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Record should not contain “redirect” more than once. This record has {1} “redirect” terms..
        /// </summary>
        public static string RedirectDoesntOccurMoreThanOnceErrorMessage {
            get {
                return ResourceManager.GetString("RedirectDoesntOccurMoreThanOnceErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Record should not contain both &apos;redirect&apos; and &apos;all&apos;..
        /// </summary>
        public static string RedirectModifierAndAllMechanismNotValidErrorMessage {
            get {
                return ResourceManager.GetString("RedirectModifierAndAllMechanismNotValidErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: A DNS response should not be larger than 450 bytes in order to work with services which don&apos;t support DNS over TCP. This response was {1} bytes..
        /// </summary>
        public static string ShouldBeSmallEnoughForUdp {
            get {
                return ResourceManager.GetString("ShouldBeSmallEnoughForUdp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SPF specification limits the amount of DNS lookups for a record to 10. This record currently has {0} which will likely cause SPF failures..
        /// </summary>
        public static string ShouldNotHaveMoreThan10QueryLookupsErrorMessage {
            get {
                return ResourceManager.GetString("ShouldNotHaveMoreThan10QueryLookupsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The use of the mx mechanism is not recommended.
        /// </summary>
        public static string ShouldNotUseMxInfoMessage {
            get {
                return ResourceManager.GetString("ShouldNotUseMxInfoMessage", resourceCulture);
            }
        }
    }
}
