//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailCheck.Spf.Poller.Expansion {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SpfExpansionMarkdownResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpfExpansionMarkdownResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MailCheck.Spf.Poller.Expansion.SpfExpansionMarkdownResource", typeof(SpfExpansionMarkdownResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FailedARecordQueryErrorMessage {
            get {
                return ResourceManager.GetString("FailedARecordQueryErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FailedMxRecordQueryErrorMessage {
            get {
                return ResourceManager.GetString("FailedMxRecordQueryErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FailedSpfRecordQueryErrorMessage {
            get {
                return ResourceManager.GetString("FailedSpfRecordQueryErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The term `{0}` is causing a DNS query to a parent SPF record..
        /// </summary>
        public static string RecursionDetectedErrorMessage {
            get {
                return ResourceManager.GetString("RecursionDetectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This MX record has over ten A record results which is not allowed.
        ///
        ///[From the SPF RFC:](https://tools.ietf.org/html/rfc7208#section-4.6.4)
        ///
        ///`When evaluating the &quot;mx&quot; mechanism, the number of &quot;MX&quot; resource
        ///records queried is included in the overall limit of 10 mechanisms/
        ///modifiers that cause DNS lookups as described above.  In addition to
        ///that limit, the evaluation of each &quot;MX&quot; record MUST NOT result in
        ///querying more than 10 address records – either &quot;A&quot; or &quot;AAAA&quot;
        ///resource records.  If this limit is [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TooManyARecordsErrorMessage {
            get {
                return ResourceManager.GetString("TooManyARecordsErrorMessage", resourceCulture);
            }
        }
    }
}
